esphome:
  name: esp32c3-mqtt-sr04m-2
  friendly_name: esp32c3-mqtt-sr04m-2
  includes:
    - uart_rcwl_1655.h

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    version: latest

logger:

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password

mqtt:
#  broker: "ae4c2f987ce94b4f9dc96f270d00e096.s1.eu.hivemq.cloud"  # Ganti dengan IP broker MQTT (misalnya HiveMQ atau Mosquitto)
  broker: "iotsmarthome.my.id"
  port: 8883
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  topic_prefix: "esp32c3"
  birth_message:
    topic: "esp32c3/status"
    payload: "online"
  will_message:
    topic: "esp32c3/status"
    payload: "offline"
  on_message:
    - topic: "esp32c3/relay/set"
      then:
        - lambda: |-
            ESP_LOGD("MQTT", "Received MQTT Relay Command");
  skip_cert_cn_check: false
  idf_send_async: true
  certificate_authority: |
    -----BEGIN CERTIFICATE-----
    MIIFazCCA1OgAwIBAgIRAIIQz7DSQONZRGPgu2OCiwAwDQYJKoZIhvcNAQELBQAw
    TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
    cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMTUwNjA0MTEwNDM4
    WhcNMzUwNjA0MTEwNDM4WjBPMQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJu
    ZXQgU2VjdXJpdHkgUmVzZWFyY2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBY
    MTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAK3oJHP0FDfzm54rVygc
    h77ct984kIxuPOZXoHj3dcKi/vVqbvYATyjb3miGbESTtrFj/RQSa78f0uoxmyF+
    0TM8ukj13Xnfs7j/EvEhmkvBioZxaUpmZmyPfjxwv60pIgbz5MDmgK7iS4+3mX6U
    A5/TR5d8mUgjU+g4rk8Kb4Mu0UlXjIB0ttov0DiNewNwIRt18jA8+o+u3dpjq+sW
    T8KOEUt+zwvo/7V3LvSye0rgTBIlDHCNAymg4VMk7BPZ7hm/ELNKjD+Jo2FR3qyH
    B5T0Y3HsLuJvW5iB4YlcNHlsdu87kGJ55tukmi8mxdAQ4Q7e2RCOFvu396j3x+UC
    B5iPNgiV5+I3lg02dZ77DnKxHZu8A/lJBdiB3QW0KtZB6awBdpUKD9jf1b0SHzUv
    KBds0pjBqAlkd25HN7rOrFleaJ1/ctaJxQZBKT5ZPt0m9STJEadao0xAH0ahmbWn
    OlFuhjuefXKnEgV4We0+UXgVCwOPjdAvBbI+e0ocS3MFEvzG6uBQE3xDk3SzynTn
    jh8BCNAw1FtxNrQHusEwMFxIt4I7mKZ9YIqioymCzLq9gwQbooMDQaHWBfEbwrbw
    qHyGO0aoSCqI3Haadr8faqU9GY/rOPNk3sgrDQoo//fb4hVC1CLQJ13hef4Y53CI
    rU7m2Ys6xt0nUW7/vGT1M0NPAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNV
    HRMBAf8EBTADAQH/MB0GA1UdDgQWBBR5tFnme7bl5AFzgAiIyBpY9umbbjANBgkq
    hkiG9w0BAQsFAAOCAgEAVR9YqbyyqFDQDLHYGmkgJykIrGF1XIpu+ILlaS/V9lZL
    ubhzEFnTIZd+50xx+7LSYK05qAvqFyFWhfFQDlnrzuBZ6brJFe+GnY+EgPbk6ZGQ
    3BebYhtF8GaV0nxvwuo77x/Py9auJ/GpsMiu/X1+mvoiBOv/2X/qkSsisRcOj/KK
    NFtY2PwByVS5uCbMiogziUwthDyC3+6WVwW6LLv3xLfHTjuCvjHIInNzktHCgKQ5
    ORAzI4JMPJ+GslWYHb4phowim57iaztXOoJwTdwJx4nLCgdNbOhdjsnvzqvHu7Ur
    TkXWStAmzOVyyghqpZXjFaH3pO3JLF+l+/+sKAIuvtd7u+Nxe5AW0wdeRlN8NwdC
    jNPElpzVmbUq4JUagEiuTDkHzsxHpFKVK7q4+63SM1N95R1NbdWhscdCb+ZAJzVc
    oyi3B43njTOQ5yOf+1CceWxG1bQVs5ZufpsMljq4Ui0/1lvh+wjChP4kqKOJ2qxq
    4RgqsahDYVvTH9w7jXbyLeiNdd8XM2w9U/t7y0Ff/9yi0GE44Za4rF2LN9d11TPA
    mRGunUHBcnWEvgJBQl9nJEiU0Zsnvgc/ubhPgXRR4Xq37Z0j4r7g1SgEEzwxA57d
    emyPxgcYxn/eR44/KJ4EBs+lVDR3veyJm+kXQ99b21/+jh5Xos1AnX5iItreGCc=
    -----END CERTIFICATE-----

output:
  - platform: gpio
    pin: GPIO8
    inverted: true
    id: led_output

switch:
#   - platform: output
#     name: "LED Onboard"
#     output: led_output
#     state_topic: "esp32c3/relay/state"
#     command_topic: "esp32c3/relay/set"
#     retain: true
    
  - platform: gpio
    name: "Relay"
    pin: 
      number: 4
      inverted: true
      mode: 
        output: True
        open_drain: True
    restore_mode: ALWAYS_OFF
    state_topic: "esp32c3/relay/state"
    command_topic: "esp32c3/relay/set"
    retain: true
    on_turn_on:
      - output.turn_on: led_output
    on_turn_off:
      - output.turn_off: led_output

web_server:
  port: 80
  version: 3
  local: true
  include_internal: true
  auth:
    username: "admin"
    password: "admin"

captive_portal:

uart:
  id: my_uart
  tx_pin: GPIO21  
  rx_pin: GPIO20
  baud_rate: 9600

sensor:
  # Sensor suhu internal ESP32-C3 (Opsional, hanya untuk memantau suhu chip)
  - platform: internal_temperature
    name: "Suhu ESP32-C3"
    # state_topic: "esp32c3/suhu"
    update_interval: 10s

  - platform: custom
    lambda: |-
      auto my_sensor = new UltrasonicSensor(id(my_uart));
      App.register_component(my_sensor);
      return {my_sensor};
    sensors:
      name: "Ultrasonic Distance"
      unit_of_measurement: "cm"
      accuracy_decimals: 2
      # state_topic: "esp32c3/ultrasonic"
